primary:
  persistence:
    enabled: true
    size: 10Gi

replica:
  replicaCount: 1   # disable replicas

auth:
  username: postgres
  password: postgres
  database: postgres

initdbScripts:
  create-lakefs.sql: |
    CREATE DATABASE lakefs;
